Action 'get-build-version' updated

diff --git a/get-build-version/action.yml b/get-build-version/action.yml
--- a/get-build-version/action.yml
+++ b/get-build-version/action.yml
@@ -25,6 +25,12 @@ outputs:
 runs:
   using: composite
   steps:
+    - id: check-required-inputs
+      run: |
+        if [ ( "${{ inputs.versioning-file }}" == "" ) ]; then
+          echo "ERROR: Path to the versioning file is required!" && exit 1
+        fi
+      shell: bash
     - id: release
       run: 'echo "value=$( echo "$( grep --extended-regexp "version" "${{ inputs.versioning-file }}" | grep --only-matching --perl-regexp "(?P<major>(0|[1-9][0-9]*))\.(?P<minor>(0|[1-9][0-9]*))" )" )" >> $GITHUB_OUTPUT'
       shell: bash
